### ISSUE TITLE
Parentheses incorrect replacement in regexp expression

### ISSUE THREAD

**Issue by andry81** [daddel80/notepadpp-multireplace#41]
File:

```txt
c:\dir1\|aaa (bbb) ccc
#> d:\dirA\ddd
c:\dirB\|aaa (bbb) ccc
#> d:\dirC\ddd
c:\dirD\|bbb) ccc
```

Want to replace to:

```txt
c:\dir1\|aaa (bbb) ccc
#> d:\dirA\ddd
d:\dirA\|aaa (bbb) ccc
#> d:\dirC\ddd
d:\dirC\|bbb) ccc
```

The expression:

```csv
Selected,Find,Replace,WholeWord,MatchCase,UseVariables,Regex,Extended
1,"^([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+))?)?)?","init({DESTDIR="""",REPLACETO=""""}); if CAP1 ~= nil and string.sub(CAP1,1,3) == ""#> "" then DESTDIR=string.match(string.sub(CAP1,4,-1),""^(.+)\\\\"") elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= ""#"" and string.len(DESTDIR) and CAP2 ~= nil then REPLACETO=DESTDIR..""\\\\|""..CAP2 end; cond(CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) and string.len(CAP2) and string.sub(CAP1,1,1) ~= ""#"" and string.len(REPLACETO), REPLACETO)",0,0,1,0,1
```

Result:

```txt
|aaa bbb ccc
#> d:\dirA\ddd
d:\dirA\|aaa bbb ccc
#> d:\dirC\ddd
d:\dirC\|bbb
```

Additionally, the first line should not be replaced, because `REPLACETO` is empty, but anyway it does replacement.

**Comment by daddel80** [comment]
Hi andry81,

I gave the regex a little update to make it shorter. The steps are the following.
1. Check CAP1 for the # sign. Depending on the sign and line number, it replaces the line.
2. Store the directory without any leading signs.

`1,"^([^\\r\\n\\|]+)(?:\\|(.+))?$","init({DESTDIR=""""}); cond(string.sub(CAP1, 1, 1) ~= ""#"" and LINE ~= 1, DESTDIR..""|""..""$2""); if string.sub(CAP1, 1, 1) == ""#"" then DESTDIR=string.sub(CAP1,4,-1) end;",0,0,1,0,1`

PS: I used $2 here instead of CAP2 because there was a bug that just dropped the brackets. Since no content validation or editing is required at this point, it just fits here. It is a workaround. I will try to fix this and will overwrite release 3.0.0.12 which i published a couple of days ago.

**Comment by daddel80** [comment]
Hi andry91,

I had a second look at the issue and saw the error you were facing. In one of your if statements, the condition was incomplete and this was leading to misbehavior with the size of REPLACETO. I corrected this, and now it works. I bolded the characters I corrected.

1,"^([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+)(?:\\|([^\\r\\n\\|]+))?)?)?","init({DESTDIR="""",REPLACETO=""""}); if CAP1 ~= nil and string.sub(CAP1,1,3) == ""#> "" then DESTDIR=string.match(string.sub(CAP1,4,-1),""^(.+)\\\\"") elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= ""#"" and string.len(DESTDIR)**>0** and CAP2 ~= nil then REPLACETO=DESTDIR..""\\\\|""..CAP2 end; cond(CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) and string.len(CAP2) and string.sub(CAP1,1,1) ~= ""#"" and string.len(REPLACETO) **> 0**, REPLACETO)",0,0,1,0,1

I have added a new version, 3.0.1.13, with a fix for the special characters in CAP. You can just copy and paste the entry above directly into the list with that version.

**Comment by andry81** [comment]
> string.len(...) > 0

https://www.lua.org/pil/2.2.html

> Beware that, unlike some other scripting languages, Lua considers **both zero and the empty string as true** in conditional tests. 

Just wow. :facepalm:
