### ISSUE TITLE
Font is VERY small

### ISSUE THREAD

**Issue by Clicketyclick** [daddel80/notepadpp-multireplace#54]
The font used by multireplace is VERY small like:
https://github.com/daddel80/notepadpp-multireplace/blob/1ff3bee03a6a9492e6b6a7057ff2009f27631a80/src/StaticDialog/resource.rc#L27

Could you please make it adjustable - or at least increase the size  to 10 or 12 ??

![multireplace_font](https://github.com/user-attachments/assets/81e9c7f4-72fa-43c4-8b80-7a0772feadad)

**Comment by daddel80** [comment]
Hi Clicketyclick,

Thanks for reporting this! Which version of MultiReplace are you currently using? I released a new version yesterday that hasn't yet been included in the Notepad++ plugin manager, so I'm curious which version you're running. If you haven't installed the latest release yet, please give it a try. You can download it here.](https://github.com/daddel80/notepadpp-multireplace/releases/tag/4.0.0.19) You have to copy one of the files unzipped into C:\Program Files\Notepad++\plugins\MultiReplace

Also, could you please click on one of the entries in the list and press F12? In the message box that appears, there should be two fonts: the standard font (which follows the plugin's size settings) and the current font (which is the default Windows size). I'd appreciate it if you could send me a screenshot of this and of the MultiReplace Window as well.

Just as a note, the RC Font settings will be overwritten.

Thanks again!

**Comment by Clicketyclick** [comment]
I will apologize for that. Tested with official version 3.1.2.18.
Have installed v. 4.0.0.19. The font is still much smaller than in Notepad++.


![multireplace_font2](https://github.com/user-attachments/assets/440b83ad-15f9-4d55-9ceb-e2cd0f69d158)

**Comment by daddel80** [comment]
Hi Erik,

No need to apologize! After looking at the screenshot, it seems the font is already a bit larger. Could you please show me the message box by pressing F12? It only works if an entry is focused in the list.

As for the text in your panel, it's not a good comparison, since the text in Notepad++ is generally a bit larger by default compared to the text in the N++ windows. A better approach would be to open the standard Notepad++ search window next to the MultiReplace window for a clearer comparison. Pls send me a screenshot of this as well.

For a quick solution, you can adjust the window scaling using the `ScaleFactor` variable in `C:\Users\<Username>\AppData\Roaming\plugins\config\MultiReplace.ini`. Try setting it to 1.1 or 1.2, then restart Notepad++ and open MultiReplace to see the result.

Let me know your findings!

**Comment by Clicketyclick** [comment]
Bingo!
Updated `%APPDATA%\plugins\config\MultiReplace.ini` with:

```diff
- ScaleFactor=1.0
+ ;ScaleFactor=1.0
+ ScaleFactor=1.5
```
Works like a chum!

> [!CAUTION]
> **ALWAYS** edit a copy of INI files since NP++ overwrites INI on exit :nerd_face:

**Comment by daddel80** [comment]
Glad to see the DPI implementation is working out! You're the first to be using version 4. Let me know if anything else comes up! 😊
