### ISSUE TITLE
Tooltips missing

### ISSUE THREAD

**Issue by conky77** [daddel80/notepadpp-multireplace#64]
in pull request #63 
I removed
* `tooltip_enable_list="Attiva lista"`
* `tooltip_disable_list="Disattiva lista"`
because the English version doesn't have them

However, without them the tooltips are untranslated.

![immagine](https://github.com/user-attachments/assets/adbb80e2-450a-43fc-9c9a-c95e47404b7b)

Is it possible to add them to the English version and restore them to the Italian one?

**Comment by daddel80** [comment]
Hi Matteo,
Thank you for reporting this. Yes, I will also add these two lines for English.
This issue wasn’t noticed earlier because the code contains a hardcoded fallback for English if entries are missing or if the alanguages.ini file is unavailable. However, I will complete this promptly.

This description is still important and will be used by the button in the lower right corner.
